config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :jobs
  get '/search', to: 'search#new'
  get '/auth/linkedin/callback', to: 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  get '/new_post', to: 'jobs#new'

  post '/jobs/post', to: 'jobs#post'
  delete '/jobs/delete', to: 'jobs#delete_job'
  get '/search/noname', to: 'search#noname'

  root 'search#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :job_users
  has_many :jobs, through: :job_users

  def self.create_with_omniauth(auth)
    @user = User.find_by(uid: auth_hash(auth)[:uid]) || User.create(auth_hash(auth))
  end

private
  def self.auth_hash(auth)
    {:provider => auth["provider"], :uid => auth["uid"], :name => auth["info"]["name"], :email => auth["info"]["email"], :img_url => auth["info"]["image"]}
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update]

  def index
    @users = User.all
  end

  def show
  end

  def edit
    @job_user = current_user.job_users.find_by_job_id(params[:job_id])
    if !@job_user.nil?
      @job_user.update(applied: true)
      redirect_to user_path
    end
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'Profile was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end


private
  def set_user
    @user = User.find(params[:id])
  end
  def user_params
      params.require(:user).permit(:name, :email)
  end
end

app/helpers/users_helper.rb
module UsersHelper

	def saved_jobs_key
		current_user.jobs.pluck(:job_key)
	end
end

app/views/users/edit.html.erb
<div class="dashContainer">
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %><br><br>
    <%= f.label :email %>
    <%= f.text_field :email %><br><br>

  </div>

  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>
</div>

app/views/users/show.html.erb
<div class="dashContainer">

    <img src= <%= @user.img_url || "http://www.genengnews.com/app_themes/genconnect/images/default_profile.jpg" %> height="100" width="100">
    <div class="userAvatar"><h2><%= @user.name %></h2><br>
    <p><%= @user.email %></p><br>
    <%= link_to("Edit Profile", edit_user_path) %></div>
    <br><br><br>
    <% @user.jobs.all.each do |job| %><br>
      <%= job.position %><br>
      <%= job.city.name %><br>
      <%= job.company %><br>
      <%= link_to "Visit Job Listing", job.url %><br>
      <% @applied_job = @user.job_users.find_by_job_id(job.id) %>

      <% if @applied_job.applied %>
        <p>Applied</p>
      <% else %>
        <div class="update_apply">
        <%= form_tag(edit_user_path, method: :get) do %>
        <%= hidden_field_tag(:job_id, value=job.id) %>
        <%= submit_tag "Applied?" %>
        <% end %>
        </div>
      <% end %>
      <% counter = job.job_users.where(applied:true)  %>
      <% if counter.size > 0 %>
        <% if counter.size == 1 %>
          1 person has applied
        <% else %> %>
          <%= counter.size %> people have applied.
        <% end %>
      <% else %>
        No one has applied yet.
      <% end %>
      <div class="delete">
        <%= form_tag(job_path, method: 'delete') do %>
        <%= hidden_field_tag(:job_id, value=job.id) %>
        <%= submit_tag "Delete Job" %>
        <% end %>
      </div><br>
  <% end %>

  <% @listing = Job.where(creator_id: current_user.id) %>
  <% if @listing.count > 0 %>
    <h4><b>Job you posted</b></h4><br>
    <% @listing.each do |listing| %>
      <div class="Job_listing">
      <ul> <b>Company:</b> <%= listing.company %></ul>
      <ul> <b>Position:</b> <%= listing.position %></ul>
      <ul> <b>Description:</b> <%= listing.description %></ul>
      <ul><a href = <%= listing.url %> > Visit Website</a></ul><br>
      <%= form_tag('/jobs/delete', method: 'post') do %>
        <%= hidden_field_tag(:job_id, value=listing.id) %>
        <%= submit_tag "Delete Job" %>
      <% end %>
      </div>
    <% end %>
  <% end %>
</div>